### PR TITLE
Portuguese Translation

### PR DESCRIPTION
**Pull request by PauloASilva**
The `2017/pt-pt` directory contains:

* Markdown contents translated to Portuguese
* Images in the `images` sub-directory were also translated to Portuguese
* The editable OWASP Top 10 2017 official template `OWASP Top 10-2017_pt-pt.odp`
* The final OWASP Top 10 2017 Portuguese version `OWASP Top 10-2017_pt-pt.pdf`

Conflicts are not expected. 
Please let me know if some changes are required.

Cheers,
Paulo A. Silva

### CODE REVIEW

**Comment by sslHello** [comment]
Congratulations for the Portuguese Version of the OWASP Top 10!
Thank you for your great volunteerism!

Cheers
Torsten

**Comment by PauloASilva** [comment]
Hi @sslHello,
Sorry about that, but can we move the PT translation maste files to the root directory as with all other translations?

Check [PR #465][1].

Cheers,
Paulo A. Silva

[1]: https://github.com/OWASP/Top10/pull/465

**Comment by Emciu** [comment]
> The `2017/pt-pt` directory contains:
> 
>     * Markdown contents translated to Portuguese
> 
>     * Images in the `images` sub-directory were also translated to Portuguese
> 
>     * The editable OWASP Top 10 2017 official template `OWASP Top 10-2017_pt-pt.odp`
> 
>     * The final OWASP Top 10 2017 Portuguese version `OWASP Top 10-2017_pt-pt.pdf`
> 
> 
> Conflicts are not expected.
> Please let me know if some changes are required.
> 
> Cheers,
> Paulo A. Silva
Thx

**Comment by Emciu** [comment]
Thx

**Pull request merged**
