### PR TITLE
Initial French translation

### PR DESCRIPTION
**Pull request by SPoint42**
This is the first and initial translation for French langage. We need a final review ASAP by French community. 

But, mostly this pull request is to see if we can integrate on the build and if the rendering is mostly nice before going head and announce the translation. 

We know there is some images who are not translated. If we have the sources or the version of the text to translate we will do

### CODE REVIEW

**Comment by SPoint42** [comment]
@vanderaj, @infosecdad @Neil-Smithline @sslHello  : You can contact me on my OWASP mail for the images if needed.

**Comment by sslHello** [comment]
Hi Sebastien, 

Thank you for your translating efforts.
> 
> @vanderaj, @infosecdad @Neil-Smithline @sslHello : You can contact me on my OWASP mail for the images if needed.

All images are taken from the pptx file, please feel free to use 'Top10/2017/translations/OWASP Top 10-2017_Template_DIN-A4.pptx'. I'll give you also a ping from my OWASP mail address.

I've tried to approve your pull request:
* There seems to be a conflict in '2017/fr/0xa4-xxe.md': Plesae tell me in which way you'd like to get the conflicts resolved or just do it yourself.
* I've tried to exclude changes to two English files:
   ~ OWASP-Top-10-2017-en.html
   ~ OWASP-Top-10-2017-en.docx  
  Hoping this works when the above conflict on the 'XXE' File is solved.

Thank you and cheers
Torsten

**Comment by SPoint42** [comment]
@sslHello : Done, I resolve conflicts. You could merge on master

**Comment by sslHello** [comment]
Approved Initial French Translation

**Pull request merged**
