### PR TITLE
FR translation 2017 Top10

### PR DESCRIPTION
**Pull request by Evtloglvl**
First batch
regarding 0x10 as a French version, shouldn t we link to ANSSI eBios ?
https://www.ssi.gouv.fr/administration/management-du-risque/la-methode-ebios-risk-manager/

### CODE REVIEW

**Comment by brainlulz** [comment]
@Evtloglvl Would be great to add the eBios source with a little explanation like "french method to help companies identifying and understanding their risks".
I can add it at the end if you want.

**Comment by sslHello** [comment]
@SPoint42 
Hi Sebastian, could you review this request, please. 
Thank you.

Cheers
Torsten

**Comment by SPoint42** [comment]
can be merged

**Comment by vanderaj** [comment]
Thank you!

**Pull request merged**
