### PR TITLE
Destroying of Session identifiers

### PR DESCRIPTION
**Pull request by drwetter**
... and avoiding encouragements of JWT denylists at the server side. See #544.

### CODE REVIEW

**Comment by jmanico** [comment]
JWT deny lists are a fundamental part of the JWT security ecosystem and I object to minimizing or discouraging their use.

**Comment by jmanico** [comment]
Look at Okta's docs. They certainly provide ways to revoke access tokens or both refresh and access tokens.

https://developer.okta.com/docs/guides/revoke-tokens/revokeatrt/#revoke-only-the-access-token

**Review by vanderaj — APPROVED** [review]
Approved.

**Comment by vanderaj** [comment]
Add this to master. https://developer.okta.com/docs/guides/revoke-tokens/revokeatrt/#revoke-only-the-access-token

**Pull request merged**
