### PR TITLE
French translation of 0x01-about-owasp.md

### PR DESCRIPTION
**Pull request by Shosta**
You can find the french translation the 0x01-about-owasp.md part.
Let me know if that needs any change.

### CODE REVIEW

**Comment by SPoint42** [comment]
Could you please add it to the french repo ? 

Thanks

**Comment by Shosta** [comment]
What do you mean by the french repo?
As I read the source were fork to the [FR2013 PPTX Version](https://github.com/OWASP/Top10/tree/master/FR2013%20PPTX%20Version) but I don't see any "0x01-about-owasp.md" or something similar in there.
Should I update the powerpoint file that is in the FR2013 PPTX Version folder?

**Comment by SPoint42** [comment]
Commit to my repo top10 and not owasp/top10.

I will merge all after the translation to the main repo

This is to not pollute owasp repo

Le 10 août 2018 19:16, Rémi Lavedrine <notifications@github.com> a écrit :

What do you mean by the french repo?
As I read the source were fork to the FR2013 PPTX Version<https://github.com/OWASP/Top10/tree/master/FR2013%20PPTX%20Version> but I don't see any "0x01-about-owasp.md" or something similar in there.
Should I update the powerpoint file that is in the FR2013 PPTX Version folder?

**Comment by Shosta** [comment]
Ok clear

**Comment by Shosta** [comment]
I can't fork you repo as it is already forked from OWASP/Top10.
It redirects me to the OWASP/Top10 repo.
So I would not be able to make a Pull request to your repo.
I'll try to clone your repo tomorrow and then update it.

**Comment by Shosta** [comment]
I can't push to your repo.
I got this : 
``remote: Permission to SPoint42/Top10.git denied to Shosta.
I cloned your repo as I can't fork it (it redirects me to the OWASP/Top10 repo I already forked).
I need a clear way to add my change to some repo.
Could you provide a clear method to push change to some repo that is made for this?
Pull request is avaiable for the OWASP Top10 repo, it looks like a good method. If you want something else, I think it must be documented somewhere (I can help on that if required).

**Comment by SPoint42** [comment]
I will add you this day. And sent you the go to push

Le 11 août 2018 11:37, Rémi Lavedrine <notifications@github.com> a écrit :

I can't push to your repo.
I got this :
``remote: Permission to SPoint42/Top10.git denied to Shosta.
I cloned your repo as I can't fork it (it redirects me to the OWASP/Top10 repo I already forked).
I need a clear way to add my change to some repo.
Could you provide a clear method to push change to some repo that is made for this?
Pull request is avaiable for the OWASP Top10 repo, it looks like a good method. If you want something else, I think it must be documented somewhere (I can help on that if required).

**Comment by Shosta** [comment]
Ok great, thank you.

**Comment by FyndhornElder** [comment]
Shosta : great job, but a few remarks.
- as far as I know, we are supposed to use as much as possible the 13th french release, as it has been fully validated. We should change things only when needed. Your translation is quite different (although fully valid)
Ligne 9 : beware, a _standard_ in english is a "norme" in french. 
Ligne 12 : _cheat sheets_ are translated in 13' by 'aide mémoire'.
But I feel like there is no major change in this page since 2013...

**Comment by Shosta** [comment]
Could you provide the link to it?
@SPoint42 do you approve that we must translate something else that the ".md" files that are located in the "fr" folder of the repo?

**Comment by SPoint42** [comment]
Rémi, you have been added to  https://github.com/SPoint42/Top10


Please just translate the MD files ! others formats are generated automatically via a shell script



[https://avatars3.githubusercontent.com/u/7026262?s=400&v=4]<https://github.com/SPoint42/Top10>

GitHub - SPoint42/Top10: Official French OWASP Top 10 ...<https://github.com/SPoint42/Top10>
github.com
GitHub is where people build software. More than 28 million people use GitHub to discover, fork, and contribute to over 85 million projects.





—

Ce mail est 100% RGPD compliant
Sébastien Gioria  +336 70 59 11 44<https://outlook.office.com/owa/?path=/mail/sentitems> – AppSecFR® - Vos Spécialistes en Sécurité Applicative
https://www.linkedin.com/in/gioria –  https://twitter.com/Spoint
Expert près la Cour d’Appel de Poitiers
OWASP French Leader




________________________________
De : Rémi Lavedrine <notifications@github.com>
Envoyé : samedi 11 août 2018 22:43
À : OWASP/Top10
Cc : sebastien gioria; Mention
Objet : Re: [OWASP/Top10] French translation of 0x01-about-owasp.md (#445)


Could you provide the link to it?
@SPoint42<https://github.com/SPoint42> do you approve that we must translate something else that the ".md" files that are located in the "fr" folder of the repo?

**Comment by FyndhornElder** [comment]
Rémi : you could use the .pptx version, but I prefer the pdf one : https://github.com/OWASP/Top10/blob/master/2013/OWASP%20Top%2010%20-%202013%20French.pdf
(copy-paste easier)

**Comment by Shosta** [comment]
Hello @SPoint42, I pushed the translation on the french repository as you asked from the OWASP/Top10 repository.
Do you review and merge it or is it someone else that is supposed to do that?

**Comment by SPoint42** [comment]
please close

**Comment by Shosta** [comment]
Done

**Comment by sslHello** [comment]
Sorry, I did not mean this one. Sorry I may have got confused my mailes from your other reporitory, that I've also received on my mobile client during my holidays.
I've tried to reopen it, but the pull request has been already deleated.
=> Please reopen and it will be merged (of corse!)
Salutations
Torsten

**Comment by sslHello** [comment]
Please read also comment to #447

**Pull request closed without merging**
