### PR TITLE
This is the final & reviewed Russian version of OWASP Top 10

### PR DESCRIPTION
**Pull request by JZDLin**

### CODE REVIEW

**Comment by JZDLin** [comment]
@oxdef @KvanTTT
Как только решим, что все вопросы улажены, можно тут попросить sslHello закомитить и выложить на сайт OWASP (если конечно, это не может сделать @oxdef).
ОК?

**Comment by JZDLin** [comment]
@sslHello Please, do not merge this PR until we confirm that our review is finished.

**Comment by sslHello** [comment]
@JZDLin Hi Jay, please send me also a personal message when you are ready. A am getting so much emails by github as beeing 'mentioned'. So it might happen that I don't see the right one...
Cheers Torsten

**Comment by oxdef** [comment]
Great! I have no objection to the merging.

**Comment by KvanTTT** [comment]
The same for me.

**Comment by JZDLin** [comment]
@sslHello @oxdef @KvanTTT 
Hi there,
I've just added some minor corrections, so the PDF and PPTX versions of Top 10 2017 are ready for merging and publishing on the OWASP website.

**Comment by sslHello** [comment]
Congratulations for getting Russian Version of the OWASP Top 10 ready for merging and publishing!

**Pull request merged**
