### PR TITLE
Fr translation 0x02 foreword

### PR DESCRIPTION
**Pull request by Shosta**
Here is the french translation of the 0x02-foreword.md file.
Tell me if you find this accurate or if I should make some changes.

### CODE REVIEW

**Comment by SPoint42** [comment]
Could you please add it to the french repo ? 

Thanks

**Comment by FyndhornElder** [comment]
Hello shosta.
So far, I just merged my own translations into SPoint42 ' s fork (SPoint42/Top 10), where they are supposed to be reviewed before any merge to the main Owasp/Top 10. But I may be wrong... I am curently waiting for some directions from him. Just as you, it seems.

**Comment by Shosta** [comment]
Indeed, still waiting.
I am not translating any other files before I know what is the proper process for the ones I already translated. :smile:

**Comment by SPoint42** [comment]
please close

**Comment by Shosta** [comment]
Done

**Comment by sslHello** [comment]
Sorry, I did not mean this one. Sorry I may have got confused my mailes from your other reporitory, that I've also received on my mobile client during my holidays.
I've tried to reopen it, but the pull request has been already deleated.
=> Please reopen and it will be merged (of corse!)
Salutations
Torsten

**Comment by sslHello** [comment]
Please read also comment to #447

**Pull request closed without merging**
