### PR TITLE
Gitbook - Top 10 2021

### PR DESCRIPTION
**Pull request by vanderaj**

### CODE REVIEW

**Comment by mackowski** [comment]
@Naramsim this PR is for reusing GT Actions from cheatsheet project to build OWASP top 10 webpage. Do you want to take part in this?

**Comment by Naramsim** [comment]
Sure, where can I help?

**Comment by mackowski** [comment]
@vanderaj want to reuse build process from cheatsheets to generate webpage for top 10. But it does a lot more than they need. For top 10 just a simple to view OWASP Top 10 list on the left hand side, A00 - A11 is needed https://github.com/OWASP/Top10/tree/master/2021/en.
They does not need indexes, spellcheck, linting, RSS feed etc.

**Comment by Naramsim** [comment]
Hello @vanderaj @mackowski, 

from what I understood you wanna create a website for showing the new Top10. Ideally, this website should be built with MkDocs and fully deployed with Github.

So here is my take: We start from scratch and do not use the files (which are super messy) of the Cheatsheet repo. We create a website that supports i18n and we build a pipeline for deploying it. Nice and clean.

I opened https://github.com/OWASP/Top10/pull/528 to show you how could we build the website. The important part is that i18n is supported, as I see in the past years you had numerous translations. This is the [`mkdocs.yml`](https://github.com/OWASP/Top10/blob/e89a99843d9826df4d1052590a374fb4f90415e1/website/mkdocs.yml) file and it looks super clean. Translated pages are organized by extension (`file_name.fr.md`) and not by folder.

I suggest you try out and see by yourself the outcome of my PR, you can follow the instructions on the PR for spinning up a local version. The site supports 3 languages and some pages are translate. Pages that miss a translation are displayed in the default language (`en`).

Let me know if you like my approach, and if so, we can start building and deploying the website together.

**Comment by Naramsim** [comment]
top10fr

Here is a screenshot of my PR. You can see the A01 vulnerability in French. Vulnerabilities from A02 to A10 weren't translated, thus they show the English text on the left side.

**Comment by mackowski** [comment]
@Naramsim I like it. Thank you!
@vanderaj what do you think about it?

**Comment by mackowski** [comment]
@vanderaj what do you think about it?

**Comment by vanderaj** [comment]
This is awesome.  I will accept it and bring the text to your PR and merge

**Comment by vanderaj** [comment]
Argh

**Comment by Naramsim** [comment]
Hi everyone,

I'll try to work on the website these days. At some point we will need the top10 translated in the various languages, are those documents available?

**Pull request merged**
