### PR TITLE
Create owasp_top10_hcl_appscan_2021_submission.json

### PR DESCRIPTION
**Pull request by sperlis**
This is the CWE statistics submission by HCL AppScan. Data contains statistics for the years 2017-2021 (to date).

### CODE REVIEW

**Review by vanderaj — COMMENTED** [review]
@infosecdad Can you please review and approve this submission?

**Comment by Emciu** [comment]
Ok

**Comment by Emciu** [comment]
[Uploading Management_examiner's_report_November 2018.pdf…]()

**Comment by Emciu** [comment]
Is

**Review by Emciu — COMMENTED** [review]
Ok

**Pull request merged**
